name: FT_RT_VOL2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run_application_macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - run: make
      - run: cd test
      - run: make