name: FT_RT_VOL2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run_application_macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - run: curl -fsSL https://rawgit.com/kube/42homebrew/master/install.sh | zsh
      - run: brew install jsoncpp
      - run: make